### PR TITLE
faster ancestry_path method

### PR DESCRIPTION
**Pull request by dush**
reversing array of strings is faster than reversing array of ActiveRecord models

### CODE REVIEW

**Comment by seuros** [comment]
Can you provide some benchmarks ?

**Comment by dush** [comment]
https://gist.github.com/dush/599d2092205908848306
> Calculating -------------------------------------
> original ancestry_path   382.000  i/100ms
>    new ancestry_path     5.311k i/100ms
> 
> -------------------------------------------------
> original ancestry_path   4.114k (± 5.6%) i/s -     20.628k
>    new ancestry_path     80.554k (± 5.3%) i/s -    403.636k
> 
> Comparison:
>    new ancestry_path:    80553.6 i/s
> original ancestry_path:     4114.0 i/s - 19.58x slower

**Comment by seuros** [comment]
Awesome.

**Comment by mceachen** [comment]
Thanks for the PR!

**Pull request merged**
