### PR TITLE
Change requirement for Ruby version back to 2.0.0

### PR DESCRIPTION
**Pull request by anduong**

### CODE REVIEW

**Comment by mceachen** [comment]
Waiting for https://travis-ci.org/mceachen/closure_tree/builds/89482237

(btw, why did you close this PR?)

**Comment by seuros** [comment]
We dropped support for old version of ruby and rails. 
Anyone with an updated version of rails can use updated  Ruby aswell.

**Comment by anduong** [comment]
@mceachen Big thanks from our team!!! Can we have your email to contact later?

Thanks for your enthusiastic support :)

**Comment by anduong** [comment]
@mceachen Can you republish the gem to Rubygems.org to update its metadata? Thanks.

**Pull request merged**
